
# -----------  Agents  -----------

[[agents]]
id = "bob"
name = "Bob"
public_address = "HcScI8Rcf6da3Wan9fKkqWwtCgbiitzb9MDV3CeUeXzpr659PO5gO6oFaZ9kuxa"
key_file = "keys/bob.key"

# -----------  DNA  -----------


[[dnas]]
id = "cointoss_dna"
file = "dna-src/dist/dna-src.dna.json"
# hash = "Qm328wyq38924y"
# ???

[[instances]]
id = "cointoss-rust"
dna = "cointoss_dna"
agent = "bob"

[instances.logger]
type = "simple"
file = "app_spec.log"

[instances.storage]
type = "memory"


[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3402
[[interfaces.instances]]
id = "cointoss-rust"

# -----------  UI  -----------

[[ui_bundles]]
id = "main"
root_dir = "./ui2"
# hash = "Qm000"
# ???

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3002
dna_interface = "websocket_interface"

# -----------  Networking  -----------

[network]
n3h_path = "n3h"
n3h_persistence_path = "./../../"
bootstrap_nodes = ["wss://10.0.0.139:62863/?a=HcSCipricGo5qow4iukDByKo9Tdi7dvutJ6StDqSv3d7pyzw3yMt3guNpRgu8wz"]

# -----------  Networking instructions  -----------

# To get networking running requires the following steps:
# - run `cd n3h && npm install && npm run boostrap && cd ..`

# - If you are the first node then start the conductor and take careful note of the line that
#	begins with `READY! tcp://127.0.0.1:43859 [...]
#	You will need to copy the contents of the array and send it to the nodes you plan to network with.
# - If you are a joining node then paste the contents from the first node in to the bootstrap_nodes field above



[logger]
type = "debug"
[[logger.rules.rules]]
color = "red"
exclude = false
pattern = "^err/"

[[logger.rules.rules]]
color = "white"
exclude = false
pattern = "^debug/dna"

[[logger.rules.rules]]
exclude = true
pattern = "^debug/reduce"

[[logger.rules.rules]]
exclude = false
pattern = ".*"
