
# -----------  Agents  -----------

[[agents]]
id = "alice"
name = "Alice"
public_address = "HcSCIMW7Wezsfc5qv4a6Bi5GOBwqyzyh9WtBakC8d7k7afo57fHnci78Zwoffgr"
key_file = "keys/alice.key"

# Q: Where do I get the agent address before spawning it?

# -----------  DNA  -----------


[[dnas]]
id = "cointoss_dna"
file = "dist/cointoss-rust.dna.json"
hash = "Qm328wyq38924y"
# Q: Where do I get this?

[[instances]]
id = "cointoss-rust"
dna = "cointoss_dna"
agent = "alice"

[instances.logger]
type = "simple"
file = "app_spec.log"

[instances.storage]
type = "memory"


[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3401
[[interfaces.instances]]
id = "cointoss-rust"

# -----------  UI  -----------

[[ui_bundles]]
id = "main"
root_dir = "./ui"
# hash = "Qm000"
# Q: Where to get the hash?

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3001
dna_interface = "websocket_interface"

# -----------  Networking  -----------

[network]
n3h_path = "n3h"
n3h_persistence_path = "./../../"
bootstrap_nodes = []

# -----------  Networking instructions  -----------

# To get networking running requires the following steps:
# - run `cd n3h && npm install && npm run boostrap && cd ..`

# - If you are the first node then start the conductor and take careful note of the line that
#	begins with `READY! tcp://127.0.0.1:43859 [...]
#	You will need to copy the contents of the array and send it to the nodes you plan to network with.
# - If you are a joining node then paste the contents from the first node in to the bootstrap_nodes field above



[logger]
type = "debug"
[[logger.rules.rules]]
color = "red"
exclude = false
pattern = "^err/"

[[logger.rules.rules]]
color = "white"
exclude = false
pattern = "^debug/dna"

[[logger.rules.rules]]
exclude = false
pattern = "^debug/reduce"

[[logger.rules.rules]]
exclude = false
pattern = ".*"
